from rest_framework import serializers

class SurvivalPredictionSerializer(serializers.Serializer):
    age_at_diagnosis = serializers.FloatField(required=True, help_text="Age at Diagnosis")
    neoplasm_histologic_grade = serializers.FloatField(required=True, help_text="Neoplasm Histologic Grade")
    her2_status = serializers.FloatField(required=True, help_text="HER2 Status")
    er_status = serializers.FloatField(required=True, help_text="ER Status")
    pr_status = serializers.FloatField(required=True, help_text="PR Status")
    tumor_size = serializers.FloatField(required=True, help_text="Tumor Size")
    tumor_stage = serializers.FloatField(required=True, help_text="Tumor Stage")
    lymph_nodes_examined_positive = serializers.FloatField(required=True, help_text="Lymph nodes examined positive")
    mutation_count = serializers.FloatField(required=True, help_text="Mutation Count")
    nottingham_prognostic_index = serializers.FloatField(required=True, help_text="Nottingham prognostic index")
    inferred_menopausal_state = serializers.FloatField(required=True, help_text="Inferred Menopausal State")
    overall_survival_months = serializers.FloatField(required=True, help_text="Overall Survival (Months)")
    relapse_free_status_months = serializers.FloatField(required=True, help_text="Relapse Free Status (Months)")
    tmb_nonsynonymous = serializers.FloatField(required=True, help_text="TMB (nonsynonymous)")
    brca1 = serializers.FloatField(required=True, help_text="BRCA1")
    brca2 = serializers.FloatField(required=True, help_text="BRCA2")
    tp53 = serializers.FloatField(required=True, help_text="TP53")
    erbb2 = serializers.FloatField(required=True, help_text="ERBB2")
    esr1 = serializers.FloatField(required=True, help_text="ESR1")
    pgr = serializers.FloatField(required=True, help_text="PGR")
    akt1 = serializers.FloatField(required=True, help_text="AKT1")
    pik3ca = serializers.FloatField(required=True, help_text="PIK3CA")
    mki67 = serializers.FloatField(required=True, help_text="MKI67")
    cdh1 = serializers.FloatField(required=True, help_text="CDH1")
    bcl10 = serializers.FloatField(required=True, help_text="BCL10")
    cfh = serializers.FloatField(required=True, help_text="CFH")
    rbm14 = serializers.FloatField(required=True, help_text="RBM14")
    taok2 = serializers.FloatField(required=True, help_text="TAOK2")
    dusp11 = serializers.FloatField(required=True, help_text="DUSP11")
    iscu = serializers.FloatField(required=True, help_text="ISCU")
    marchf6 = serializers.FloatField(required=True, help_text="MARCHF6")
    mob3b = serializers.FloatField(required=True, help_text="MOB3B")
    dnajb6 = serializers.FloatField(required=True, help_text="DNAJB6")
    atg12 = serializers.FloatField(required=True, help_text="ATG12")
